### ISSUE TITLE
Simple documentation of GardenRootsWeb

### ISSUE THREAD

**Issue by kisaacs** [UA-SRC-data/geo-visualization#3]
Add README to UA-SRC-data/GardenRootsWeb with instructions for how to launch it with some web server.

**Comment by kv9699** [comment]
The documentation was written and committed, but it needs to be merged into UA-SRC-data/GardenRootsWeb.
It seems that I do not have access to commit to UA-SRC-data/GardenRootsWeb.

**Comment by kv9699** [comment]
It is in the new branches.
